spring:
  application:
    name: user-data-aggregator-service

server:
  port: 8080

springdoc:
  swagger-ui.path: /swagger
  api-docs.path: /api-docs
  packages-to-scan: com.tsa.userdataaggregatorservice
  swagger-ui.tryItOutEnabled: true
  swagger-ui.operationsSorter: method
  swagger-ui.tagsSorter: alpha
  swagger-ui.filter: true